name: dimagkharab
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.5+2
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.4+2
  carousel_pro: ^1.0.0
  shared_preferences: ^0.5.8
  carousel_slider: ^2.2.1
  provider: ^4.0.0+1




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/at2.png
    - images/atproject.png
    - images/newt.png
    - images/profile.png
    - images/i1.jpg
    - images/i2.jpg
    - images/i3.jpeg
    - images/i4.jpeg
    - images/i5.jpg
    - images/c1.jpg
    - images/c2.jpg
    - images/c3.png
    - images/c4.jpg
    - images/c5.jpg
    - images/w1.jpg
    - images/w2.jpg
    - images/w3.jpg
    - images/w4.jpg
    - images/w5.jpg
    - images/co1.jpg
    - images/co2.jpg
    - images/co3.jpg
    - images/co4.jpg
    - images/co5.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Abel
      fonts:
         - asset: fonts/Abel-Regular.ttf
           weight: 200
#          style: italic
#         - asset: fonts/Schyler-Italic.ttf
    - family: Roboto
      fonts:
         - asset: fonts/Roboto-Bold.ttf
           weight: 700
#         - asset: fonts/Roboto-MediumItalic.ttf
 #          weight: 500
 #        - asset: fonts/Roboto-LightItalic.ttf
  #         weight: 300

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
